# Generated by Django 3.1 on 2020-08-22 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todoitem_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
