# Generated by Django 3.1 on 2020-08-26 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_todoitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='user',
        ),
    ]
